apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music
  creationTimestamp: null
  name: spring-music.apps.local.20250130.741.15928
spec:
  refName: spring-music.apps.local
  releasedAt: "2025-01-30T07:46:43Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: ttl.sh/ci/containerapp-spring-music@sha256:c7dfa21d7966fc808634dfccd223c26aea9930a8068ca3e8f6dea1d7ed030464
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20250130.741.15928
