apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music
  creationTimestamp: null
  name: spring-music.apps.local.20250128.836.12170
spec:
  refName: spring-music.apps.local
  releasedAt: "2025-01-28T08:39:01Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: ttl.sh/ybhagwan/app-accelerator@sha256:7d901ac55e9a331b46a8791be6bdce0bf102db6edba99659f67a1204f7e57bee
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20250128.836.12170
