apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-music
  creationTimestamp: null
  name: spring-music.apps.local.20250130.915.35573
spec:
  refName: spring-music.apps.local
  releasedAt: "2025-01-30T09:19:00Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: ttl.sh/ci/containerapp-spring-music@sha256:c8be210e304a27fda2b61db8917c3c8514c81c3f52245cb86877ef083a5f6ad8
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20250130.915.35573
